### ISSUE TITLE
List

### ISSUE THREAD

**Issue by NerfThis123** [2piradians/Minewatch#13]
.When using Mei's cryo-freeze hero mods are able to walk through you but don't damage you
.When using Junkrat's mine sometimes the mine activator button replaces the weapon and the weapon and the button goes away
.Make it so that keep inventory is on when your in a team
.Every time I did and respsawn it turns me back to creative mode

**Comment by Furgl** [comment]
What version of Minewatch and Forge are you using and do you have any other mods installed?

Mei's cryofreeze protect you from taking damage, mobs can still walk through you; I may give the crystal collision in the future. 
The Junkrat bug should be fixed in the recent versions. 
You can turn keep inventory on yourself. 
It respawns you in the world's default gamemode.

**Comment by NerfThis123** [comment]
what version of forge you suggest and i'm using the latest version of Minecraft 1.12.2

**Comment by NerfThis123** [comment]
Im useing 3.10.3

**Comment by Furgl** [comment]
I tend to use the recommended version of Forge. If you can find a consistently reproducible way to trigger that Junkrat bug in Minewatch v3.10.3 with the recommended Forge version, then I can look into it.

**Comment by NerfThis123** [comment]
okay
