### ISSUE TITLE
Bug: Teams not behaving like Teams

### ISSUE THREAD

**Issue by HydroPotato5** [2piradians/Minewatch#17]
Hi there! This mod is great and all, but I realised that in Minewatch-1.12.X-3.11, I can hurt entities in the same team as me. I can also attack enemy Minewatch hero mobs, but they do not fight back, only using their self-healing abilities, or healing each other. 
Mods I have installed with Minewatch:
jei_1.12.2-4.8.0.114
NotEnoughItems-1.12-2.4.0.231-universal
CodeChickenLib-1.12-3.1.3.313-universal
Hwyla-1.8.22-B37_1.12
AppleCore-mc1.12.2-3.0.0
AppleSkin-mc1.12-1.0.9
journeymap-1.12.2-5.5.2
Mouse-Tweaks-Mod-1.12.1
OptiFine_1.12.2_HD_U_C9
torohealth-1.12.2-11
None of these should affect behaviours between entities though (since they are client-side addons that do not introduce any new entities, items or blocks), but I thought I'd bring them up just in case.
I have tried exiting teams, reenetering teams and moving entities to different teams, but nothing seems to fix it. Please help! Thanks you all!

**Comment by Furgl** [comment]
Hiya!
With Minewatch v3.11, weapons and hero mobs now obey the "AllowFriendlyFire" rule with teams (to give the option to create FFA teams). You'll have to disable that rule (because Minecraft has it set to true by default for some stupid reason). 
I'm not sure why hero mobs wouldn't attack you unless you have them set not to attack players in the config or you're in creative mode.
