### ISSUE TITLE
Healer problems

### ISSUE THREAD

**Issue by HydroPotato5** [2piradians/Minewatch#20]
With Minewatch 3.12:
- Healing cannot be dispensed to teammates (from any hero) but upon removing them from my team, I can heal them.
- I also cannot heal myself, whether it's as Lucio or with Moira's heal orb

**Comment by Furgl** [comment]
It sounds like your team has friendly fire on (which is default if the team was created via commands or in an earlier Minewatch version). You can disable that with `/scoreboard teams option <team> friendlyfire false`.

There is currently a bug with Lucio and Moira not being able to heal themselves while on a team with friendly fire enabled; that'll be fixed in the next update. Thanks for reporting it!
